# Generated by Django 6.0.1 on 2026-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dietplan_dietuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss'), ('maintain', 'Maintain Weight')], max_length=20),
        ),
    ]
